---
title: "Problema Secretaria"
author: "Juan Pablo Vanegas Moreno - 1000640165"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
#r es el número de secretarias que se entrevistan al comienzo pero se dejan pasar.
# N: Numero de secretarias en la poblacion Estan numeradas de 1 a N. La mejor
# es la #1, la segunda mejor es la 2, etc.
# Criterio: Deje pasar las primeras k=0,1,...,N-1.
# Luego escoja la secretaria que sea mejor que las
# anteriores. En caso que no, se queda con la
# ultima secretaria.


decision <- function(secuencia, r){
  # secuencia: El orden en que aparecen las secretarias para la entrevista
  # r: Numero de secretarias que se entrevistan al comienzo pero se dejan pasar.
  N <- length(secuencia)
  secu1 <- secuencia[1:r] #secretarias que se dejan pasar
  secu2 <- secuencia[(r+1):N] # secretarias que se entrevistan
  la.mejor <- 0
  while(la.mejor == 0){
    # Si la mejor esta en el grupo que se deja pasar
    # nos quedaremos con la ´ultima secretaria
    if(min(secu1) == 1) 
      la.mejor <- secuencia[N]
    else{
      temp <- secu1
      i <- 1
      while(i <= length(secu2) & la.mejor == 0){
        if(secu2[i] < min(temp)){
          la.mejor <- secu2[i]
        } else{
          temp <- c(temp, secu2[i])
          i <- i + 1
        } # fin del else
      } #FIN DEL FOR
    } #fin del else
  } # fin del while
  return(la.mejor)
} #termina la función 'decision'

```

```{r}
simula.con.1.criterio <- function(N, r, Nsim = 10000){
  arreglos <- matrix(rep(1:N, Nsim), ncol = N, byrow = TRUE)
  arreglos <- t(apply(arreglos, 1, sample, N))
  res <- apply(arreglos, 1, decision, r)
  print(mean(res))
}

```

```{r}
 simula.con.1.criterio(20,0)
```

# Criterio de costo maximo

Se añaden dos parametros

costo.entrevista: costo de entrevistar a una secretaria costo.maximo: costo maximo que se puede gastar en entrevistas

```{r}
# N: Numero de secretarias en la poblacion
# Estan numeradas de 1 a N. La mejor
# es la #1, la segunda mejor es la 2, etc.
# Criterio: Deje pasar las primeras k=0,1,...,N-1.
# Luego escoja la secretaria que sea mejor que las
# anteriores sin pasarse del costo maximo. 
# En caso que no, se queda con la ultima secretaria.

decision.costos <- function(secuencia, r, costo.entrevista, costo.maximo){
  N <- length(secuencia)
  secu1 <- secuencia[1:r]
  secu2 <- secuencia[(r+1):N]
  mejor_secretaria <- 0
  costo_total <- 0 # conteo de costo total 
  
  while (mejor_secretaria == 0 && costo.maximo >= costo.entrevista) {
    if (min(secu1) == 1) {
      mejor_secretaria <- secuencia[N]
    } else {
      temp <- secu1
      i <- 1
      while (i <= length(secu2) && mejor_secretaria == 0) {
        if (secu2[i] < min(temp)) {
          mejor_secretaria <- secu2[i]
        } else {
          temp <- c(temp, secu2[i])
          i <- i + 1
        }  # Fin del else
      } # Fin del while anidado
    } # Fin del else
    costo_total <- costo_total + costo.entrevista
    costo_maximo <- costo.maximo - costo.entrevista
  } # Fin del while
  
  return(list(secretaria = mejor_secretaria, costo_total = costo_total))
}

```

```{r}
simula.con.1.criterio.costos <- function(N, r, costo.entrevista, costo.maximo, Nsim = 10000){
  arreglos <- matrix(rep(1:N, Nsim), ncol = N, byrow = TRUE)
  arreglos <- t(apply(arreglos, 1, sample, N))
  res <- apply(arreglos, 1, function(x) decision.costos(x, r, costo.entrevista, costo.maximo))
  print(mean(sapply(res, function(x) x$secretaria)))
  print(mean(sapply(res, function(x) x$costo_total)))
  
  }

```

```{r}
simula.con.1.criterio.costos(20, 5, 300, 1000)
```

# Acercamiento costos por entrevista
```{r}
decision_costo <- function(secuencia, r, c){
  # secuencia: El orden en que aparecen las secretarias para la entrevista
  # r: Numero de secretarias que se entrevistan al comienzo pero se dejan pasar.
  # c: Costo de cada entrevista
  N <- length(secuencia)
  secu1 <- secuencia[1:r] #secretarias que se dejan pasar
  secu2 <- secuencia[(r+1):N] # secretarias que se entrevistan
  la.mejor <- 0
  costo_total <- 0
  while(la.mejor == 0){
    # Si la mejor esta en el grupo que se deja pasar
    # nos quedaremos con la ´ultima secretaria
    if(min(secu1) == 1){
      la.mejor <- secuencia[N]
      costo_total <- N * c
    } else{
      temp <- secu1
      i <- 1
      while(i <= length(secu2) & la.mejor == 0){
        costo_total <- costo_total + c
        if(secu2[i] < min(temp)){
          la.mejor <- secu2[i]
        } else{
          temp <- c(temp, secu2[i])
          i <- i + 1
        } # fin del else
      } #FIN DEL FOR
    } #fin del else
  } # fin del while
  return(list("La mejor secretaria" = la.mejor, "Costo total" = costo_total))
} #termina la función 'decision_costo'

```



```{r}
decision_costo <- function(secuencia, r, c){
  # secuencia: El orden en que aparecen las secretarias para la entrevista
  # r: Numero de secretarias que se entrevistan al comienzo pero se dejan pasar.
  # c: Costo de cada entrevista
  N <- length(secuencia)
  secu1 <- secuencia[1:r] #secretarias que se dejan pasar
  secu2 <- secuencia[(r+1):N] # secretarias que se entrevistan
  la.mejor <- 0
  costo_total <- 0
  while(la.mejor == 0){
    # Si la mejor esta en el grupo que se deja pasar
    # nos quedaremos con la ´ultima secretaria
    if(min(secu1) == 1){
      la.mejor <- secuencia[N]
      costo_total <- N * c
    } else{
      temp <- secu1
      i <- 1
      while(i <= length(secu2) & la.mejor == 0){
        costo_total <- costo_total + c
        if(secu2[i] < min(temp)){
          la.mejor <- secu2[i]
        } else{
          temp <- c(temp, secu2[i])
          i <- i + 1
        } # fin del else
      } #FIN DEL FOR
    } #fin del else
  } # fin del while
  return(list("La mejor secretaria" = la.mejor, "Costo total" = costo_total))
} #termina la función 'decision_costo'

```


```{r}
simula.con.costo <- function(N, r, c, Nsim = 10000){
  arreglos <- matrix(rep(1:N, Nsim), ncol = N, byrow = TRUE)
  arreglos <- t(apply(arreglos, 1, sample, N))
  res <- apply(arreglos, 1, function(x) decision_costo(x, r, c))
  res <- do.call(rbind, res)
  res <- as.data.frame(res)
  colnames(res) <- c("La mejor secretaria", "Costo total")
  res$`La mejor secretaria` <- as.numeric(as.character(res$`La mejor secretaria`))
  res$`Costo total` <- as.numeric(as.character(res$`Costo total`))
  print(paste("La mejor secretaria promedio:", mean(res$`La mejor secretaria`)))
  print(paste("Costo total promedio:", mean(res$`Costo total`)))
}

```


```{r}
simula.con.costo(20, 5, 300)
```

